apiVersion: apps/v1
kind: Deployment
metadata:
  name: friend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: friend
  template:
    metadata:
      labels:
        app: friend
    spec:
      containers:
        - name: friend
          image: jnavacar/friend-service:main
---
apiVersion: v1
kind: Service
metadata:
  name: friend-srv
spec:
  selector:
    app: friend
  ports:
    - name: friend
      protocol: TCP
      port: 8082
      targetPort: 8082